version: "3.3"

services: 

  web:
    build: 
      context: ./projects/store-app
      dockerfile: Dockerfile

    env_file: 
      - ".env.web.dev"

    ports: 
      - "8000:80"

    volumes: 
      - "./projects/store-app:/home/app/src"

    depends_on: 
      - redis
      - payment_service
      # - store_app_postgres

  payment_service:
    
    build: 
      context: ./projects/payment-service
      dockerfile: Dockerfile

    env_file: 
      - ".env.payment.dev"

    ports: 
      - "9000:80"

    volumes: 
      - "/home/qz/projects/django-online-store/auction-project/auction_payment_service:/home/app/src"

    depends_on:
      - redis
      # - payment_postgres

  redis:
    image: bitnami/redis:latest

    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=VBvc6yBGT0T2GAwn64aZLkh4ioNS8Z8v
      - REDIS_MASTER_PASSWORD=VBvc6yBGT0T2GAwn64aZLkh4ioNS8Z8v

    ports:
      - 6379

  # store_app_postgres:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
  #     POSTGRES_PASSWORD: test1234$$
  #   ports:
  #     - 5432


  # payment_postgres:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
  #     POSTGRES_PASSWORD: test1234$$
  #   ports:
  #     - 5432
